version: '3.1'
services:
 default-rabbitmq: 
  container_name: default-delayed-rabbitmq 
  image: heidiks/rabbitmq-delayed-message-exchange 
  expose: 
    - 15672 
    - 5672 
  ports: 
    - 5672:5672 
    - 15672:15672 
  volumes: 
    - rabbitmq-datavolume:/Users/onurkapcik/git/dockerfiles/rabbitmq/data

volumes:
  rabbitmq-datavolume: