version: '3.1'
services:
  mssql:
    image: mcr.microsoft.com/azure-sql-edge:latest
    environment:
      - "ACCEPT_EULA=1"
      - "MSSQL_SA_PASSWORD=Password1!"
    ports:
      - "1433:1433"
    volumes:
      - "mssql-azuresql-edge-datavolume:/Users/onurkapcik/git/dockerfiles/mssql/data"

volumes:
    mssql-azuresql-edge-datavolume:
