version: '3.1'
services:
  default-mysql:
    container_name: default-mysql
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
    expose: 
      - 3306
    ports:
      - 3306:3306
    volumes:
      - mysql-datavolume:/Users/onurkapcik/git/dockerfiles/mysql/data
volumes:
  mysql-datavolume:
