
version: '3.8'

services:
  cache:
    image: redis
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 120 1 --loglevel warning --requirepass 7b0evpiTayUA9kw0VYLRyWzc0mxPChtU
    volumes: 
      - cache:/Users/onurkapcik/git/dockerfiles/redis/data
volumes:
  cache:
    driver: local
