version: '3.8'

services:
  cache:
    image: redis
    ports:
      - '6379:6379'
    command: >
      redis-server 
        --include /usr/local/etc/redis/redis.conf 
        --save 120 1 
        --loglevel warning 
        --appendonly yes 
        --maxmemory 256mb 
        --maxmemory-policy allkeys-lru
    volumes: 
      - ./data:/data
      - ./redis.conf:/usr/local/etc/redis/redis.conf
      - ./users.acl:/etc/redis/users.acl

